#Taha Imzilen & Julien Barde - IRD
#52North WPS annotations
# wps.des: id = knitrCompile, title = Generic R code to compile knitr documents, abstract =  This script is meant to enable the compilation of any knitr Code using open data and source code avilable through URLS or made available by complying with a template of sub-repositories coming along the knitr main code within a zip file;
# wps.in: id = upload_report, type = string, title = , value = "/main.Rnd";
# wps.in: id = report_parametrization, type = string, title = Data URL, value = "http://mdst-macroes.ird.fr:8080/constellation/WS/wfs/tuna_atlas";
# wps.out: id = Pdfresult, type = string, title = result file path list;

#STEP: load knitr Package
require(knitr)
#STEP 1: Specify the working directory of the machine running the process
mywd <- '/home/julien/SVNs/GIT/IRDTunaAtlas/'
# mywd <- '/home/taha/R/monR-2013/esp_travail/IRDTunaAtlas/reports/'

#STEP 2: file.inout variable will store the prefix used for the names of the 2 default files expected to run the compilation:
#   * "name.Rnw" for the knitR code, 
#   * "name.R" to set up the R environment required to comple the knitR Code,
#   * "name.tex" will be generated by compiling "name.Rnw" with this file
file.inout <-'KnitrTest2'
# file.inout <-'ICCAT_Report_BFTE'
# file.inout <-'Report_Sardara'

#STEP 3: Execution of the function which compiles the knitR code
Run_Report(path.inout = mywd,file.inout =file.inout, zip_file = zip, show.pdf=F)
